### ISSUE TITLE
Documentation inconsistent

### ISSUE THREAD

**Issue by krausandre** [TYPO3-Initiatives/content-block-registration-api#10]
@typecat 

1) Default.xml vs. EditorInterface.xlf
In the [Content Block registration draft](https://github.com/TYPO3-Initiatives/structured-content/blob/master/Documentation/ContentBlocks/ContentBlockRegistration.md) sometimes we talking about Default.xml and sometimes the EditorInterface.xlf
Maybe you can give us a short description on that. 

2) Or in Translation is invalid
We cannot provide an 'OR' on this point:
_Title for the CType are taken from src/Language/EditorInterface.xlf **or** src/Language/Default.xlf of the Content Block package_

**Comment by typecat** [comment]
See [FAQ](https://github.com/TYPO3-Initiatives/structured-content/blob/master/Documentation/ContentBlocks/FAQ.md#is-it-possible-to-use-different-language-files-for-frontend-and-backend): It is possible to provide 2 language files named EditorInterface.xlf and Frontend.xlf in case there is a necessity to split labels for backend and frontend. By default the file Default.xlf is used.
