### ISSUE TITLE
Document necessary protection for non-public files 

### ISSUE THREAD

**Issue by jonaseberle** [TYPO3-Initiatives/content-block-registration-api#16]
- [ ] have an .htaccess example
- [ ] (optional) have an nginx example

Could be based on https://github.com/TYPO3/TYPO3.CMS/tree/master/typo3/sysext/install/Resources/Private/FolderStructureTemplateFiles

**Comment by krausandre** [comment]
Discussion with Matthias:

Thoughts: 

- Add to documentation: yes
- Think of Resources/Public and Resources/Private vs. src and dist. How to go on?

**Comment by jonaseberle** [comment]
Why is that assigned to me? I'll just close it as you checked it already...
