### ISSUE TITLE
Migrate content blocks registration draft as official documentation in RST format

### ISSUE THREAD

**Issue by typecat** [TYPO3-Initiatives/content-block-registration-api#23]

**Comment by jonaseberle** [comment]
Could you add the webhook for getting it rendered on docs.typo.org? 
https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocForExtension/Migrate.html#migrate

I'll just tag a version 0.1 since that's required for the webhook.

**Comment by typecat** [comment]
I've updated all configuration files described in the link above. The next step would be to get approval from the TYPO3 Documentation Team, but therefore we need to release it to TER first.

Blocked by #36

**Comment by typecat** [comment]
Released to TER. The next step would be to get approval from the TYPO3 Documentation Team.

**Comment by typecat** [comment]
Documentation is released: https://docs.typo3.org/p/typo3-contentblocks/contentblocks-reg-api/1.0/en-us/
