### ISSUE TITLE
Remedy extension scanner false positive `addStyleSheet()`

### ISSUE THREAD

**Issue by jonaseberle** [TYPO3-Initiatives/content-block-registration-api#28]
The extension scanner currently shows 

`Classes/EventListener/AssetRenderer/EnableCbNamespace.php Call to method "addStyleSheet()"`

as a match to ` Deprecation: #85735 - Various method and property in DocumentTemplate`
and ` Breaking: #87193 - Deprecated functionality removed`.

It matches this line https://github.com/TYPO3-Initiatives/content-block-registration-api/blob/master/Classes/EventListener/AssetRenderer/EnableCbNamespace.php#L67 

This false positive can probably be solved by adjusting the extension scanner ruleset in Core.

If not, `// @extensionScannerIgnoreLine` could be used...

**Comment by typecat** [comment]
Done, also escaped multiple false-positives when calling `$this->logger->error()` method.
