### ISSUE TITLE
Generate FlexForm based on the EditorInterface.yaml of the Content Block package

### ISSUE THREAD

**Issue by typecat** [TYPO3-Initiatives/content-block-registration-api#3]
## Technical Story

Generate FlexForm based on the EditorInterface.yaml of the Content Block package

### Acceptance criteria

- [x] All fields apart from Collection configured in the EditorInterface.yaml of the Content Block package are present in the FlexForm
- [x] The FlexForm is valid
- [x] The FlexForm is saved in `tt_content.content_block`

### Notes

- To resolve the EditorInterface fields to FlexForm / TCA see [mapping documentation](https://github.com/TYPO3-Initiatives/structured-content/blob/master/Documentation/ContentBlocks/FieldTypeMapping.md).

**Comment by krausandre** [comment]
@typecat 
We net to discuss if we want to go on with flexforms, because it seems that this do not support the whole TCA options. So the idea is, maybe we can switch over to a kind of real TCA simulation. But I have no idea at the moment, what this means and how it works.

**Comment by typecat** [comment]
As discussed I have moved the requirements for the [collection field type](https://github.com/TYPO3-Initiatives/content-block-registration-api/issues/21) and [palettes](https://github.com/TYPO3-Initiatives/content-block-registration-api/issues/22) to own issues, because those are larger issues that can be solved separately and don't necessarily block this feature.
