### ISSUE TITLE
Test with languages

### ISSUE THREAD

**Issue by jonaseberle** [TYPO3-Initiatives/content-block-registration-api#32]
# As an *editor*, I want to *translate* a ContentBlock, so I can provide my site information for people in foreign countries. 

## Acceptance criteria
- [ ] The content block could be used in connected and translated mode
- [ ] Every field of a content block is translateable
- [ ] I can use a different image in the foreign language, if I could enter an image
- [ ] The original image is used, if I don't translate the image 

## Acceptance tests
- [ ]  I can translate a content block
- [ ]  I see the original translation for every field I could translate
- [ ] The translated data is avaiable in the backend preview
- [ ] The translated data is avaiable in the frontend template
 
## Preconditions / boundary conditions
- [ ]  I have editor's permissions
- [ ]  I have permission to create a content block
- [ ]  I have permission to translate a content block

**Comment by mcmietz** [comment]
Test Copy and Connected Mode for another language. 
Both works fine for the Slider, but not for the slides. I don't see the default language hint. 
<img width="1402" alt="connected-mode-slide" src="https://user-images.githubusercontent.com/8003340/99999844-0a51c080-2dc1-11eb-9b12-dc7405775216.png">
<img width="1434" alt="connected-mode-Slider" src="https://user-images.githubusercontent.com/8003340/99999850-0cb41a80-2dc1-11eb-8a32-b187289c9528.png">
<img width="1429" alt="rename-slider-connected-mode" src="https://user-images.githubusercontent.com/8003340/99999856-0e7dde00-2dc1-11eb-9d12-234154e614c5.png">
<img width="1419" alt="Copy-mode-slider" src="https://user-images.githubusercontent.com/8003340/99999862-0f167480-2dc1-11eb-8f5c-0a4076fa7bd2.png">

**Comment by jonaseberle** [comment]
I don't think we can get the default language hint (`l10n_source`) in the FlexForm at all :(

The other parts worked fine for me, too.

**Comment by typecat** [comment]
Needs to be re-tested with the new storage method.

**Comment by jonaseberle** [comment]
Tested with the `feature-database-storage` branch:

## Acceptance criteria
- [x] The content block could be used in connected and translated mode
- [x] Every field of a content block is translateable
- [x] I can use a different image in the foreign language, if I could enter an image
- [x] The original image is used, if I don't translate the image 

## Acceptance tests
- [x]  I can translate a content block
- [x]  I see the original translation for every field I could translate
- [x] The translated data is avaiable in the backend preview
- [ ] The translated data is avaiable in the frontend template

In the frontend, results are from the standard language for Collections and Sub-collections:
![image](https://user-images.githubusercontent.com/1678001/160455492-d60e8459-b06f-46c6-8ee5-94b794d1b0f7.png)

(This is with our example CB `typo3-contentblocks_example-local`)

Cc: @krausandre
