### ISSUE TITLE
Test with workspaces

### ISSUE THREAD

**Issue by mcmietz** [TYPO3-Initiatives/content-block-registration-api#34]
# As an *chiefeditor*, I want to *publish* a ContentBlock, so the information is available for every visiter of the website.

## Acceptance criteria
- [x] The content block was added in the backend
- [x] The content block is ready for publishing

## Acceptance tests
- [x]  I see the information that one content block is under review
- [x]  I have the opportunity to publish this content block
- [x] The content block is rendered in the frontend after publishing
- [x] The content in the content block could be checked by the reviewer also inline relations like collections
- [x] The status of the content block could be set to under review again, for the editor
 
## Preconditions / boundary conditions
- [x]  I have chiefeditor's permissions
- [x]  A workspace is configured
- [x]  I have permissions for that workspace

**Comment by jonaseberle** [comment]
I couldn't leave it... This should also make Collections will show the correct state in Frontend and Backend.
