### ISSUE TITLE
Release to TER/Packagist

### ISSUE THREAD

**Issue by jonaseberle** [TYPO3-Initiatives/content-block-registration-api#36]

**Comment by typecat** [comment]
Released:
https://extensions.typo3.org/extension/contentblocks_reg_api
https://packagist.org/packages/typo3-contentblocks/contentblocks-reg-api

**Comment by jonaseberle** [comment]
This
https://github.com/TYPO3-Initiatives/content-block-registration-api/commit/f3ed3cbca68c2b65c8015527224f7e473e3d0525
uses Github Actions for publishing to TER and a local command to update version information.

(Commit message contains steps how to release, too)
