### ISSUE TITLE
Field type Multiselect: property "minitems" not implemented

### ISSUE THREAD

**Issue by typecat** [TYPO3-Initiatives/content-block-registration-api#42]
## Acceptance criteria

- [ ]  Property "minitems" for field type "Multiselect" transfers to property "minitems" in the corresponding generated Flexform

**Comment by krausandre** [comment]
Note: eval required it seems that this is not supportet by TCA. The field is required by setting minitems greater then 0.
See https://docs.typo3.org/m/typo3/reference-tca/10.4/en-us/ColumnsConfig/Type/selectMultipleSideBySide.html
