### ISSUE TITLE
Bugfix Content Block Builder

### ISSUE THREAD

**Issue by krausandre** [TYPO3-Initiatives/content-block-registration-api#45]
## HTML Templates: 

- [ ] no foreach if image max item is 1
- [ ] text html parse function if rte enabled

## Flexform parsing

- [ ] if no header field, use the first text field in collections instead of "no title" (if possible)
- [ ] use the specific content block icon to collection items

**Comment by typecat** [comment]
I have split this issue, because the title wasn't really speaking and the bugs mentioned above had no relation to each other.
