### ISSUE TITLE
Field type Collection: minItems and maxItems property not implemented

### ISSUE THREAD

**Issue by typecat** [TYPO3-Initiatives/content-block-registration-api#53]
## Acceptance criteria

- [x]  Setting a `minItems` value in a Collection  field in the EditingInterface.yaml is applied to the resulting TCA configuration
- [x]  Setting a `maxItems` value in a Collection  field in the EditingInterface.yaml is applied to the resulting TCA configuration
- [x]  It is not possible to create more Collection children than set in the `maxItems` property
- [x]  The content block cannot be saved if less Collection children are created than defined in the `minItems` property

## Technical remarks

- See [docs](https://docs.typo3.org/p/typo3-contentblocks/contentblocks-reg-api/1.0/en-us/IntegratorManual/YamlReference/Types/Collection/Index.html)

**Comment by krausandre** [comment]
Already implemented in v2. Additional: if property required is set, work-a-round with minItems is implemented.
