### ISSUE TITLE
Field types Date, Datetime, Time: selected value resets on save

### ISSUE THREAD

**Issue by typecat** [TYPO3-Initiatives/content-block-registration-api#58]
Selecting a value in a field of type `Date`, `Datetime` or `Time` works fine, but if the content block is saved , the value given in the `lower` property is applied instead.

## Acceptance criteria

- [x]  The value entered in a field of type `Date`, `Datetime` or `Time` is saved correctly in the flexform

**Comment by krausandre** [comment]
Yes, this is implemented in v2. One of the main issue was that the example yaml config was wrong. But this is also fixed.
