### ISSUE TITLE
Add field for storing Content Block data to tt_content

### ISSUE THREAD

**Issue by typecat** [TYPO3-Initiatives/content-block-registration-api#6]
## Technical Story

Add field for storing Content Block data to `tt_content`

### Acceptance criteria

- [x] If not yet present the field `content_block` is added to `tt_content`
- [x] The field `content_block` is of type ???

**Comment by typecat** [comment]
Which type should the field have? Not sure if it should be blob or text ...
https://dev.mysql.com/doc/refman/5.7/en/blob.html

**Comment by jonaseberle** [comment]
I think TEXT is fine for XML data. I'll close this for the time being.

**Comment by typecat** [comment]
I'm fine with that.
