### ISSUE TITLE
Field type Multiselect: properties "minItems", "maxItems" and "required" missing in Content Blocks Builder GUI

### ISSUE THREAD

**Issue by typecat** [TYPO3-Initiatives/content-block-registration-api#64]
## Acceptance criteria

- [x]  It is possible to set the `minItems` property for the field type `Multiselect` in the Content Blocks Builder GUI and it is applied to the resulting EditingInterface.yaml
- [x] - [ ]  It is possible to set the `maxItems` property for the field type `Multiselect` in the Content Blocks Builder GUI and it is applied to the resulting EditingInterface.yaml
- [x] - [ ]  It is possible to set the `required` property for the field type `Multiselect` in the Content Blocks Builder GUI and it is applied to the resulting EditingInterface.yaml

## Technical remarks

- See [docs](https://docs.typo3.org/p/typo3-contentblocks/contentblocks-reg-api/1.0/en-us/IntegratorManual/YamlReference/Types/Multiselect/Index.html)
- Corresponds with #42

**Comment by krausandre** [comment]
Note: eval required it seems that this is not supportet by TCA. The field is required by setting minitems greater then 0.
See https://docs.typo3.org/m/typo3/reference-tca/10.4/en-us/ColumnsConfig/Type/selectMultipleSideBySide.html

**Comment by typecat** [comment]
Fixed: If an element of type `MultiSelect` is required and the `minItems` property is not set, set `minItems = 1`.
