### ISSUE TITLE
As a developer, I want this to be PHP 8 compatible

### ISSUE THREAD

**Issue by jonaseberle** [TYPO3-Initiatives/content-block-registration-api#76]
# As a *who*, I can *what*, so that *why*.

## Acceptance criteria

- [ ] Works error-free in PHP 8
 
## Acceptance tests

- [ ] CI checks compatibility with PHP 8

**Comment by typecat** [comment]
I ran some rector check for PHP 8.0 and TYPO3 11.5. Also I applied some checks for empty field properties, so that the TCA field service and the CB processor don't fail after upgrading from TYPO3 10.4 to 11.5.
Upgrade worked fine and there were no content errors.

**Comment by typecat** [comment]
The others did some more testing and the CGL pipeline runs without errors now.
